import type { SaleWithItems } from '@shared/types'

export function sampleSale(): SaleWithItems {
  return {
    id: 'sample',
    number: 1024,
    started_at: new Date().toISOString(),
    completed_at: new Date().toISOString(),
    subtotal: 4490,
    discount: 500,
    total: 3990,
    payment_method: 'efectivo',
    cash_received: 5000,
    change_given: 1010,
    cash_session_id: 'sample',
    cashier_id: null,
    voided: 0,
    payments: [{ method: 'efectivo', amount: 3990, cash_received: 5000, change_given: 1010 }],
    items: [
      {
        product_id: 'p1',
        name_snapshot: 'Coca-Cola 500ml',
        price_snapshot: 1290,
        cost_snapshot: 800,
        surcharge: 0,
        qty: 2,
        line_total: 2580,
        is_weight: 0,
        returned_qty: 0,
      },
      {
        product_id: 'p2',
        name_snapshot: 'Pan amasado unidad',
        price_snapshot: 350,
        cost_snapshot: 220,
        surcharge: 0,
        qty: 4,
        line_total: 1400,
        is_weight: 0,
        returned_qty: 0,
      },
      {
        product_id: 'p3',
        name_snapshot: 'Gomitas surtidas Premium',
        price_snapshot: 510,
        cost_snapshot: 320,
        surcharge: 0,
        qty: 1,
        line_total: 510,
        is_weight: 0,
        returned_qty: 0,
      },
    ],
  }
}
